apiVersion: apps/v1
kind: Deployment
metadata:
  name: beautifulthings
  labels:
    app: beautifulthings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beautifulthings
  template:
    metadata:
      labels:
        app: beautifulthings
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: beautifulthings
        image: docker.io/chiiph/beautifulthings:f944197
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        env:
        - name: STORE
          value: cached+gcs
        volumeMounts:
        - name: gcs
          mountPath: "/etc/gcs"
          readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
      volumes:
      - name: gcs
        secret:
          secretName: gcs
          items:
          - key: spartan-calling-218821-3348c633f71c.json
            path: gcs.json
---
kind: Service
apiVersion: v1
metadata:
  name: beautifulthings
spec:
  selector:
    app: beautifulthings
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: beautifulthings
  namespace: default
spec:
  secretName: beautifulthings-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: 'server.beautifulthings.app'
  dnsNames:
  - server.beautifulthings.app
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - server.beautifulthings.app
